services:
  discovery-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/discovery-service}
      HEARTBEAT_EXPIRY_IN_MINUTES: ${HEARTBEAT_EXPIRY_IN_MINUTES}

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: